### ISSUE TITLE
CoverageWarning: Module pyproject_api was never imported

### ISSUE THREAD

**Issue by mtelka** [tox-dev/pyproject-api#44]
When I test pyproject-api 1.4.0 ~~with Python 3.9~~ it emits this warning (pytest-cov==4.0.0,coverage==7.0.5):
```
/usr/lib/python3.9/vendor-packages/coverage/inorout.py:507: CoverageWarning: Module $(BUILD_DIR)/.tox/py39/lib/python3.9/site-packages/pyproject_api was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
```
~~When I do the same with Python 3.7 no warning is printed.~~

**Comment by gaborbernat** [comment]
We only support running the test suite with tox and no plugins. If you run the test suite in another way you're out of support.
