### ISSUE TITLE
Lingering `_backend.py` process

### ISSUE THREAD

**Issue by sk1p** [tox-dev/pyproject-api#69]
I'm not sure exactly in what circumstances this happens, but sometimes, there's a lingering `_backend.py` process, with CLI arguments `True setuptools.build_meta __legacy__`. The process takes up 100% on one CPU core. Until now, it always happened in CI, probably as part of using tox. I now got around to debugging this, and by attaching `py-spy top -p <pid-here>` to this process, I can see it spends ~100% time in `read_line`:

![image](https://user-images.githubusercontent.com/5778/232854811-9d531ab0-bb33-44d7-935a-ae975ba22fd1.png)

One scenario where this can happen, is when `stdin` is EOF:

https://github.com/tox-dev/pyproject-api/blob/b366ab1fe2e27238eefd916cc1c3c9b8a147af1b/src/pyproject_api/_backend.py#L115-L127

If `stdin` is already EOF when `read_line` is called, it returns an empty `bytearray`. Then, in the caller...

https://github.com/tox-dev/pyproject-api/blob/b366ab1fe2e27238eefd916cc1c3c9b8a147af1b/src/pyproject_api/_backend.py#L71-L74

... it loops just endlessly.

I'm not sure what's the proper fix (I didn't read enough code to understand the context) - should the `EOFError` bubble up if `content` is empty, which can then be handled in the outer loop?

**Comment by gaborbernat** [comment]
> should the EOFError bubble up if content is empty, which can then be handled in the outer loop?

I think so. But perhaps worth understanding why toxs exit is not handled and we get to this EOF 🤔

**Comment by gaborbernat** [comment]
PR welcome 👍

**Comment by sk1p** [comment]
The issue can be reproduced using the minimal tox config from https://github.com/tox-dev/tox/issues/3056, i.e. only running a `sleep` command, and then executing `killall tox` from another shell. I'll put up a PR shortly.
